### ISSUE TITLE
swiftlatex.live triggers SSL_ERROR_BAD_CERT_DOMAIN in Firefox

### ISSUE THREAD

**Issue by JobLeonard** [SwiftLaTeX/SwiftLaTeX#10]
https://github.com/SwiftLaTeX links to https://www.swiftlatex.live/. Opening the latter gives certification errors.

The markdown links to `swiftlatex.com`, so maybe the `.live` domain is outdated anyway?

**Comment by elliott-wen** [comment]
Thanks. Fixed already.

**Comment by alerque** [comment]
If the issue is fixed, the issue report can be closed I think...
