### ISSUE TITLE
source code to build cpdfetex.wasm

### ISSUE THREAD

**Issue by albertz** [SwiftLaTeX/SwiftLaTeX#12]
This could maybe be in a separate repository.
I'm also not sure if you want to include the whole Latex sources in there, or just the patch files, and build scripts.
Or is it actually already there? It's not clear to me. Some brief documentation, or just Readme with a link, would be helpful.

**Comment by kpeeters** [comment]
+1 (unless of course it's your intention to keep that a trade secret).

**Comment by elliott-wen** [comment]
It is built atop pdftex and bibtex. There is no build scripts and patches
so far.

https://github.com/SwiftLaTeX/PdfTeXLite

https://github.com/SwiftLaTeX/BibTeXLite

Will release it after cleaning up the mess.

Cheers

**Comment by cdbattags** [comment]
https://github.com/SwiftLaTeX/SwiftLaTeX/issues/12#issuecomment-562037420

Y'all are awesome, thanks! Mind writing a comment here whenever that is released?
