### ISSUE TITLE
Add option to switch from horizontal to vertical splitview

### ISSUE THREAD

**Issue by javamuc** [SwiftLaTeX/SwiftLaTeX#13]
With many people having wider monitor it would be useful to be able to switch the split view. Or if possible split it over two monitors. Write on one check on the other.

**Comment by elliott-wen** [comment]
Yes, it has been our roadmap. Cheers

**Comment by javamuc** [comment]
Looks as if this was done, I just tried the demo version and it had vertical spit view.
