### ISSUE TITLE
biblatex support

### ISSUE THREAD

**Issue by m4lvin** [SwiftLaTeX/SwiftLaTeX#14]
It seems [biblatex](https://www.ctan.org/pkg/biblatex) (and in particular biber) is not available / not supported. Could it be added? Probably depends on unicode support?

**Comment by elliott-wen** [comment]
Hmm, two possible causes.
1. We dont have the files in our on-demand latex file server. 
2. Probably the files are designed for xetex.

Would you mind providing a snippet so i can look into it?

**Comment by m4lvin** [comment]
Do you mean an example document how to use biblatex?

```latex
\documentclass{article}
\usepackage{filecontents}
\begin{filecontents}{test.bib}
@article{hello,
  title = "Hello",
  author = "Mary Miller"
}
\end{filecontents}

\usepackage{biblatex}
\addbibresource{test.bib}

\begin{document}
A citation: \cite{hello}

\printbibliography
\end{document}
```

**Comment by elliott-wen** [comment]
Hi Malvin

I will look into it and get back to you. :)

**Comment by secretshardul** [comment]
Any updates in this regard? Has SwiftLatex been archived?

**Comment by elliott-wen** [comment]
I just open-sourced the engine, you can hack the c file if you wish. Sorry, I was overwhelmed by my job.
