### ISSUE TITLE
Dockerhub

### ISSUE THREAD

**Issue by SmithPeder** [SwiftLaTeX/SwiftLaTeX#15]
Can I suggest creating https://hub.docker.com/r/swiftlatex before anyone else, as I cannot find a user with that name? Then publishing the latest `swiftlatex/swiftlatex:latest` so people can fetch it like that.

Right now everybody has to either:
1. Pull the whole repo and build it themselves (and the build has its own `git clone` in it)
2. Copy the `DockerFile` and `docker-compose` manually, and build it like that.

**Comment by elliott-wen** [comment]
Yes. That's a nice idea. Thank you. Will look into it
