### ISSUE TITLE
Add default localHost address for wsgi  

### ISSUE THREAD

**Issue by RELNO** [SwiftLaTeX/SwiftLaTeX#16]
Great work! 

Might worth adding: open browser and run `http://0.0.0.0:3000/ (or wherever wsgi runs)` to https://github.com/SwiftLaTeX/SwiftLaTeX#run-swiftlatex-using-python3-in-3-steps as step 3.1

**Comment by elliott-wen** [comment]
Thank you. Already fixed it.
