### ISSUE TITLE
other storage

### ISSUE THREAD

**Issue by ghost** [SwiftLaTeX/SwiftLaTeX#18]
Hello,

For security reason, we can't use Google Drive or another external storage provider.
It'll be good to be able to use:

- local storage
- S3 compatible storage like minio: https://github.com/minio/minio

Regards

**Comment by elliott-wen** [comment]
We do have a local storage option. 

https://www.swiftlatex.com/oauth/login_oauth?type=sandbox <https://www.swiftlatex.com/oauth/login_oauth?type=sandbox>

Check this out. 

Files are stored in your local browser storage. But remember to backup stuff before you clear your browser history. 

Cheers
Elliott
