### ISSUE TITLE
Google Drive session signs out when browser is closed

### ISSUE THREAD

**Issue by surmeier** [SwiftLaTeX/SwiftLaTeX#19]
Desired outcome: Be able to sign in with Google and for the session to not sign out when the browser is closed. 

Reality: I can successfully sign into Google Drive through `https://www.swiftlatex.com/oauth/login_oauth?type=google` and grant the appropriate permissions, but when I quit the browser and reopen `https://www.swiftlatex.com/ide/index.html` I get an error message: `You must log in first`, and I am forced to sign in again and grant permissions again.

**Comment by elliott-wen** [comment]
Thanks for your feedback.
There is a security reason behind this.

Google grants access tokens only valid for 30 minutes. Afterward, a user
either has to re-login
or allows the application to retrieve another kind of token called refresh
token. With refresh token, the application can on behalf of the user get a
new access token whenever it wants.
Our python code chose not to store the refresh token to avoid leaking it.

I am thinking probably it will be ok to store the refresh token in users'
cookie?

Any thoughts?

Cheers
Elliott

**Comment by surmeier** [comment]
Thanks for the quick response. It seems that storing the refresh tokens in the users' cookie would be ok, but it depends on how the app is configured. You could look [here](https://auth0.com/docs/security/store-tokens) for more information.

**Comment by elliott-wen** [comment]
Wow, that's quite useful. I will look into it.
