### ISSUE TITLE
Selecting a range with the cursor should(n't)...

### ISSUE THREAD

**Issue by alerque** [SwiftLaTeX/SwiftLaTeX#2]
First off since it seems this will be the first issue ever let me set the tone by saying, wow! This is a really neat project with an innovative approach. I'm primarily reviewing it with an eye to what UIs could be built for the [SILE Typesetter](https://sile-typesetter.org/), but I can see this being really useful especially as a component to bake into other systems.

Now back to issue reporting:

Because there is a somewhat unconventional disconnect between what you are clicking on and looking and and where the keyboard input is actually getting sent, it is a little confusing to guess what will happen when clicking in the PDF. Single clicks pretty much make sense, you get a cursor.

On the other hand drag selections don't do anything sensible at all. Selecting a range of text looks like an operation is happening, but nothing does. I would either:

* disable mouse drags entirely on the canvas to make it clear it does nothing or
* actually use the start and end locations from the canvas to select the same range in the TeX source pane and have the keyboard focus there so <kbd>Backspace</kbd>, <kbd>Ctrl</kbd><kbd>C</kbd>, *et al* work as expected.

**Comment by elliott-wen** [comment]
Thanks for the feedback.

It sounds a good idea to disable selection at this stage.

Cheers
Elliott
