### ISSUE TITLE
support for collaborative edition of Latex documents

### ISSUE THREAD

**Issue by monperrus** [SwiftLaTeX/SwiftLaTeX#21]
Hi,

We're heavily using Sharelatex and Overleaf for real-time collaborative edition of Latex documents. 

Does SwiftLaTeX support collaborative edition?

Thanks! --Martin

**Comment by elliott-wen** [comment]
Hi Martin

Yes. It is, if you log in with Google account, You can share your project
with your friend, and work on it together.

But just supporting Google now. And require a relatively
sensitive permission (Full Google Drive access)

Cheers
Elliott

**Comment by alerque** [comment]
Full Google Drive access is a show stopper for me. Even though I can see the code if I ran it myself, I can't trust that other demo / live servers are running that code _and_ that they are not compromised in any way by malware etc. This is not mistrust of you personally, just a matter of good digital hygiene and operational security.

When other sharing backends or more fine grained permissions become a thing this will be interesting to test.

**Comment by monperrus** [comment]
Thanks a lot for your answer Elliott.

Is that real-time collaborative edition as in Google Doc? Do we see the changes of the other editors
within seconds?

**Comment by elliott-wen** [comment]
Yes functionally the same.

 I will upload the backend code to github within this week after my
conference paper submission deadline.

Backend is built atop sharedb.

Cheers.

**Comment by monperrus** [comment]
>  Backend is built atop sharedb.

Nice!
