### ISSUE TITLE
No pages of output.

### ISSUE THREAD

**Issue by datagridview** [SwiftLaTeX/SwiftLaTeX#22]
I opened the local version of SwiftLatex, and I searched for a resume template. After i chose one,  something went wrong when i was about to edit it.
Please help me! Thanks anyway.
![image](https://user-images.githubusercontent.com/22040727/70540909-04a79e80-1ba1-11ea-87c4-0edb240e24a5.png)

**Comment by elliott-wen** [comment]
Hi Yunfan

It is a bug, I will look into it tonight :) Thanks for your patience.
