### ISSUE TITLE
Share-volume with docker and its host

### ISSUE THREAD

**Issue by gitathrun** [SwiftLaTeX/SwiftLaTeX#23]
First thing first, great work, looking forward to the official DockerHub image.

My question is:
Is it possible to setup a share volume between docker image and the host? 

I had some legacy tex directory for some documents, is it possible to use the SwiftLaTex docker image directly on those share volume directories with docker "-v" argument and then everything shows on web browser UI? 

It might be easier for us to handle the previous created docment with git version control without recreate the project in the UI again?

Many thanks.

**Comment by elliott-wen** [comment]
Hi Gitathrun.

Our system is completely running on client-side.  (The python code over there just serves as a simple webserver). We store files on local browser session storage, Google Drive, and Dropbox.

Nevertheless, your idea seems quite useful. We will consider adding it to our roadmap.  :)

Cheers
Elliott
