### ISSUE TITLE
Fontconfig in XeTeX engine

### ISSUE THREAD

**Issue by elliott-wen** [SwiftLaTeX/SwiftLaTeX#24]
Hi Guys or girls, 

I am working on a more modern engine XeTeX. (under the engine directory).

One tricky question is about fontconfig, which may not work under WebAssembly environment.

Currently, I removed fontconfig such that the compilation can go ahead. 

But it means users who wishes to use non-standard tex fonts has to upload their fonts. Do you think it is a sensible decision?

**Comment by khaledhosny** [comment]
Would FontConfig work inside the browser anyway? It needs access to local files on the system to work.

**Comment by alerque** [comment]
If the TeX source is not on my local system and the output is not on my local system I wouldn't expect it to use fonts from my local system during compile. I would expect to have to put any font files used alongside the other document resources.
