### ISSUE TITLE
LDAP support for local integration

### ISSUE THREAD

**Issue by SoulEater45** [SwiftLaTeX/SwiftLaTeX#28]
I am really loving swiftlatex and wanted it to be a part of the working group at my university. But it would be awesome to be able to login via an ldap service where an account is automatically made for local projects. Is somehting like this planned or will I have to wait for this feature for too long?

Best regards!

**Comment by elliott-wen** [comment]
Hi There

Thanks for your encouragement.


There are many things going on recently.
We are currently enhancing our editor by reusing vs studio code  such that
we can enjoy more robust editing experience and other cool functionalities
like advanced autocomplete and git version tracking. New version is using
xelatex as backend so it supports Unicode.

We are also planing to use minio as storage backend where we may be able to
incorporate LDAP function.

It's just that we currently only have two people working on it. So we may
take more time to deliver the new version. Really appreciate your
understanding.

**Comment by elliott-wen** [comment]
We are investigating how to integrate LDAP in the new version. So SwiftLaTeX can be more easily used in education institutions
