### ISSUE TITLE
How to setup from scratch?

### ISSUE THREAD

**Issue by kingsleyluoxin** [SwiftLaTeX/SwiftLaTeX#29]
I have set up this locally. However, this repo doesn't mention how to set up back-end tex compile such as texlive. Do I have to pull a texlive docker image?

**Comment by elliott-wen** [comment]
No. This repo is self-contained. Swiftlatex unlike, overleaf, has no backend.

All the computation is done locally in browsers using WASM. 

Let me know if you have further questions.

**Comment by anagorko** [comment]
I'm leaving this comment for others that might stumble on this: I had to install mongodb (sudo apt install mongodb on Ubuntu) to get this working.
