### ISSUE TITLE
Connection refused: Cannot run with either docker container or python3 directly

### ISSUE THREAD

**Issue by DeeDiveT** [SwiftLaTeX/SwiftLaTeX#31]
Hello, I can run with neither docker container nor python3 directly in the system. Does anyone successfully run the SwiftLaTeX?

Error:
portal      | 172.19.19.1 - - [2020-03-31 10:57:53] "GET /favicon.ico HTTP/1.1" 500 456 60.152768
portal      | [2020-03-31 10:58:23,360] ERROR in app: Exception on /favicon.ico [GET]
portal      | Traceback (most recent call last):
portal      |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
portal      |     response = self.full_dispatch_request()
portal      |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
portal      |     return self.finalize_request(rv)
portal      |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1969, in finalize_request
portal      |     response = self.process_response(response)
portal      |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2268, in process_response
portal      |     self.session_interface.save_session(self, ctx.session, response)
portal      |   File "/usr/local/lib/python3.8/site-packages/flask_session/sessions.py", line 439, in save_session
portal      |     self.store.update({'id': store_id},
portal      |   File "/usr/local/lib/python3.8/site-packages/pymongo/collection.py", line 3213, in update
portal      |     return self._update_retryable(
portal      |   File "/usr/local/lib/python3.8/site-packages/pymongo/collection.py", line 854, in _update_retryable
portal      |     return self.__database.client._retryable_write(
portal      |   File "/usr/local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1490, in _retryable_write
portal      |     with self._tmp_session(session) as s:
portal      |   File "/usr/local/lib/python3.8/contextlib.py", line 113, in __enter__
portal      |     return next(self.gen)
portal      |   File "/usr/local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1823, in _tmp_session
portal      |     s = self._ensure_session(session)
portal      |   File "/usr/local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1810, in _ensure_session
portal      |     return self.__start_session(True, causal_consistency=False)
portal      |   File "/usr/local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1763, in __start_session
portal      |     server_session = self._get_server_session()
portal      |   File "/usr/local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1796, in _get_server_session
portal      |     return self._topology.get_server_session()
portal      |   File "/usr/local/lib/python3.8/site-packages/pymongo/topology.py", line 482, in get_server_session
portal      |     self._select_servers_loop(
portal      |   File "/usr/local/lib/python3.8/site-packages/pymongo/topology.py", line 208, in _select_servers_loop
portal      |     raise ServerSelectionTimeoutError(
portal      | pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused

Millions of thx in advance

**Comment by elliott-wen** [comment]
sorry this repo still at the alpha stage.
I will update it as soon as possible. Just recent national lockdown makes
everything super hard.
