### ISSUE TITLE
\includegraphics issues

### ISSUE THREAD

**Issue by davidbelius** [SwiftLaTeX/SwiftLaTeX#32]
Thank you very much for developing this fantastic tool!

I have noticed some issues with using \includegraphics:
1. pdf files included using \includegraphics do not show up in the preview, but they do show up when exported.
2. png files incuded using \includegraphics show up neither in the preview, nor when exported.

I am using https://v2.swiftlatex.com. I have attached a minimal example where these issues arise.

The project files:
[swiftlatex_project.zip](https://github.com/SwiftLaTeX/SwiftLaTeX/files/4428288/swiftlatex_project.zip)

The result of exporting:
[graph_png_export.pdf](https://github.com/SwiftLaTeX/SwiftLaTeX/files/4428274/graph_png_export.pdf)
[graph_pdf_export.pdf](https://github.com/SwiftLaTeX/SwiftLaTeX/files/4428276/graph_pdf_export.pdf)

**Comment by elliott-wen** [comment]
The latest version should have fixed this issue.
