### ISSUE TITLE
Projects cannot be loaded

### ISSUE THREAD

**Issue by pythonbobo** [SwiftLaTeX/SwiftLaTeX#34]
Hi,
I have the issue, that no projects will be correctly created. The page don't stops loading while creating. If I move backwards to the project-overview and click the project, there is only some loading circle showing up.

I created my own dockerfile because the original one wasn't working with the presented docker-compose workaround. My Dockerfile is equal to that one  
[Issue30](https://github.com/SwiftLaTeX/SwiftLaTeX/issues/30).

On my minio storage only a manifest date is created.

Here are the logs:

> 

172.17.0.1 - - [2020-05-15 08:15:26] "GET /u/op4svsorChIn34kq/ HTTP/1.1" 304 288 0.035482
172.17.0.1 - - [2020-05-15 08:15:29] "GET /project HTTP/1.1" 200 6027 0.046851
172.17.0.1 - - [2020-05-15 08:15:29] "GET /static/css/project.css HTTP/1.1" 304 289 0.018784
172.17.0.1 - - [2020-05-15 08:15:29] "GET /static/js/project.js HTTP/1.1" 304 289 0.019799
172.17.0.1 - - [2020-05-15 08:15:30] "GET /project HTTP/1.1" 200 6027 0.050605
172.17.0.1 - - [2020-05-15 08:15:30] "GET /static/js/project.js HTTP/1.1" 304 289 0.018897
172.17.0.1 - - [2020-05-15 08:15:30] "GET /static/css/project.css HTTP/1.1" 304 289 0.017721
172.17.0.1 - - [2020-05-15 08:15:34] "GET /u/43BvNR2r8Sxdt34V/ HTTP/1.1" 200 667 0.037878
172.17.0.1 - - [2020-05-15 08:15:34] "GET /u/43BvNR2r8Sxdt34V/bundle.js HTTP/1.1" 200 6183232 0.361072
172.17.0.1 - - [2020-05-15 08:15:35] "GET /u/43BvNR2r8Sxdt34V/22.bundle.js HTTP/1.1" 200 26587 0.042429
172.17.0.1 - - [2020-05-15 08:15:35] "GET /u/43BvNR2r8Sxdt34V/37.bundle.js HTTP/1.1" 200 7736 0.033381
172.17.0.1 - - [2020-05-15 08:15:35] "GET /u/43BvNR2r8Sxdt34V/e817279537a0417d042f62fbb1b99eea.gif HTTP/1.1" 200 44498 0.037781
172.17.0.1 - - [2020-05-15 08:15:35] "GET /u/43BvNR2r8Sxdt34V/34.bundle.js HTTP/1.1" 200 22186 0.031101
172.17.0.1 - - [2020-05-15 08:15:35] "GET /u/43BvNR2r8Sxdt34V/42.bundle.js HTTP/1.1" 200 3914 0.037056
172.17.0.1 - - [2020-05-15 08:15:35] "GET /u/43BvNR2r8Sxdt34V/39.bundle.js HTTP/1.1" 200 12383 0.032565
172.17.0.1 - - [2020-05-15 08:15:35] "GET /u/43BvNR2r8Sxdt34V/12.bundle.js HTTP/1.1" 200 34256 0.034597
172.17.0.1 - - [2020-05-15 08:15:35] "GET /u/43BvNR2r8Sxdt34V/0.bundle.js HTTP/1.1" 200 16930 0.027610
172.17.0.1 - - [2020-05-15 08:15:35] "GET /u/43BvNR2r8Sxdt34V/1.bundle.js HTTP/1.1" 200 19235 0.037785
172.17.0.1 - - [2020-05-15 08:15:36] "GET /u/43BvNR2r8Sxdt34V/7.bundle.js HTTP/1.1" 200 56027 0.041588
172.17.0.1 - - [2020-05-15 08:15:36] "GET /u/43BvNR2r8Sxdt34V/2.bundle.js HTTP/1.1" 200 1307036 0.217206
172.17.0.1 - - [2020-05-15 08:15:36] "GET /u/43BvNR2r8Sxdt34V/3.bundle.js HTTP/1.1" 200 46440 0.035293
172.17.0.1 - - [2020-05-15 08:15:36] "GET /u/43BvNR2r8Sxdt34V/4.bundle.js HTTP/1.1" 200 20206 0.030034
172.17.0.1 - - [2020-05-15 08:15:36] "GET /u/43BvNR2r8Sxdt34V/5.bundle.js HTTP/1.1" 200 86774 0.036285
172.17.0.1 - - [2020-05-15 08:15:36] "GET /u/43BvNR2r8Sxdt34V/33.bundle.js HTTP/1.1" 200 35649 0.034099
172.17.0.1 - - [2020-05-15 08:15:36] "GET /u/43BvNR2r8Sxdt34V/9.bundle.js HTTP/1.1" 200 22282 0.036638
172.17.0.1 - - [2020-05-15 08:15:36] "GET /u/43BvNR2r8Sxdt34V/43.bundle.js HTTP/1.1" 200 3207 0.031523
172.17.0.1 - - [2020-05-15 08:15:36] "GET /u/43BvNR2r8Sxdt34V/6.bundle.js HTTP/1.1" 200 113096 0.052128
172.17.0.1 - - [2020-05-15 08:15:36] "GET /u/43BvNR2r8Sxdt34V/44.bundle.js HTTP/1.1" 200 2827 0.026237
172.17.0.1 - - [2020-05-15 08:15:36] "GET /u/43BvNR2r8Sxdt34V/36.bundle.js HTTP/1.1" 200 27123 0.031674
172.17.0.1 - - [2020-05-15 08:15:36] "GET /u/43BvNR2r8Sxdt34V/8.bundle.js HTTP/1.1" 200 31826 0.030872
172.17.0.1 - - [2020-05-15 08:15:36] "GET /u/43BvNR2r8Sxdt34V/11.bundle.js HTTP/1.1" 200 273323 0.053292
172.17.0.1 - - [2020-05-15 08:15:36] "GET /u/43BvNR2r8Sxdt34V/10.bundle.js HTTP/1.1" 200 728062 0.129827
172.17.0.1 - - [2020-05-15 08:15:36] "GET /u/43BvNR2r8Sxdt34V/14.bundle.js HTTP/1.1" 200 124580 0.042705
172.17.0.1 - - [2020-05-15 08:15:36] "GET /u/43BvNR2r8Sxdt34V/13.bundle.js HTTP/1.1" 200 666046 0.064171
172.17.0.1 - - [2020-05-15 08:15:36] "GET /u/43BvNR2r8Sxdt34V/40.bundle.js HTTP/1.1" 200 3221 0.037594
172.17.0.1 - - [2020-05-15 08:15:37] "GET /u/43BvNR2r8Sxdt34V/15.bundle.js HTTP/1.1" 200 252039 0.047349
172.17.0.1 - - [2020-05-15 08:15:37] "GET /u/43BvNR2r8Sxdt34V/32.bundle.js HTTP/1.1" 200 30501 0.035625
172.17.0.1 - - [2020-05-15 08:15:37] "GET /u/43BvNR2r8Sxdt34V/18.bundle.js HTTP/1.1" 200 123328 0.037632
172.17.0.1 - - [2020-05-15 08:15:37] "GET /u/43BvNR2r8Sxdt34V/20.bundle.js HTTP/1.1" 200 35204 0.028809
172.17.0.1 - - [2020-05-15 08:15:37] "GET /u/43BvNR2r8Sxdt34V/16.bundle.js HTTP/1.1" 200 19179 0.036381
172.17.0.1 - - [2020-05-15 08:15:37] "GET /u/43BvNR2r8Sxdt34V/28.bundle.js HTTP/1.1" 200 118954 0.040095
172.17.0.1 - - [2020-05-15 08:15:37] "GET /u/43BvNR2r8Sxdt34V/23.bundle.js HTTP/1.1" 200 342305 0.045416
172.17.0.1 - - [2020-05-15 08:15:37] "GET /u/43BvNR2r8Sxdt34V/30.bundle.js HTTP/1.1" 200 79754 0.034224

> 

Regards

**Comment by elliott-wen** [comment]
The latest version should have fixed this issue. We have rewritten the whole system from the scratch. Cheers
