### ISSUE TITLE
Wrong port exposed?

### ISSUE THREAD

**Issue by SoulEater45** [SwiftLaTeX/SwiftLaTeX#36]
I wanted to test the new version with docker.
First I tried using the docker hub version, which did not work and a quick look in the nginx config revealed that the port is not correct that I used. I opened the provided dockerfile in the repo, to find out, you expose the port ```8080```, but the application is running on ```3000```. Than I used the provided Dockerfile to build my own image, but now the application uses port ```3011```. After exposing ```3011```, in the dockerfile, everything worked finde!
Have I done something wrong or should this be switched somehow?

**Comment by elliott-wen** [comment]
Oops. The docker file is not well tested. Sorry about that. If you have a
working docker file, could you send a pull request?

Cheers
Elliott

Mirza Arnaut <notifications@github.com> 于2020年7月2日周四 下午12:42写道：

**Comment by elliott-wen** [comment]
BTW, you could try the new version on www.swiftlatex.com.  There is a
playground option which requires no login.

Elliott Wen <jq.elliott.wen@gmail.com> 于2020年7月2日周四 下午12:51写道：

**Comment by SoulEater45** [comment]
Hi Elliott
I just made the request.
Also, when I host it myself, the buttons somehow do not work ...
Whatever I press, it won't respond to it.

Cheers
Mirza

**Comment by elliott-wen** [comment]
Oops, I will definitely look into it.

That's pretty weird, because almost all the codes are client-side
Javascript. The docker just runs a simple express http server.

Mirza Arnaut <notifications@github.com> 于2020年7月2日周四 下午1:21写道：

**Comment by SoulEater45** [comment]
Here are the logs from building the image:

<details>
  <summary>Click to expand!</summary>

```
Building apache
Step 1/7 : FROM node:12
 ---> 1fa6026dd8bb
Step 2/7 : WORKDIR /usr/src/app
 ---> Running in 804e3daa0ca5
Removing intermediate container 804e3daa0ca5
 ---> e72247afe79a
Step 3/7 : COPY package*.json ./
 ---> 9423df302a3e
Step 4/7 : RUN npm install
 ---> Running in 9f2607715230

> puppeteer@1.20.0 install /usr/src/app/node_modules/puppeteer
> node install.js


Chromium downloaded to /usr/src/app/node_modules/puppeteer/.local-chromium/linux-686378

> core-js@3.6.5 postinstall /usr/src/app/node_modules/@babel/node/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> core-js@2.6.11 postinstall /usr/src/app/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> nodemon@1.19.4 postinstall /usr/src/app/node_modules/nodemon
> node bin/postinstall || exit 0

Love nodemon? You can now support the project via the open collective:
 > https://opencollective.com/nodemon/donate

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/jest-runtime/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/jest-runner/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/jest-config/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/@jest/test-sequencer/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/@jest/reporters/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/@jest/core/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 1908 packages from 1018 contributors and audited 1924 packages in 81.461s

64 packages are looking for funding
  run `npm fund` for details

found 4648 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
Removing intermediate container 9f2607715230
 ---> ea350aaf3229
Step 5/7 : COPY . .
 ---> bfee24b8698d
Step 6/7 : EXPOSE 3011
 ---> Running in 91b16b690df3
Removing intermediate container 91b16b690df3
 ---> 8f331e99a4d0
Step 7/7 : CMD [ "npm", "run", "start:dev" ]
 ---> Running in 6caa324076ec
Removing intermediate container 6caa324076ec
 ---> 05d79ed2b4a7
```
</details>

Also, here is the docker-compose.yml file I used to get it to run.
```
version: "3.3"

services:
  apache:
    #image: swiftlatex/v2.0:latest
    build: .
    container_name: swiftlatex
    expose:
      - "3011"
    environment:
      VIRTUAL_HOST: <domain>
      LETSENCRYPT_HOST: <domain>
      LETSENCRYPT_EMAIL: <mail>
      APACHE_HTTP_PORT_NUMBER: 80
      APACHE_HTTPS_PORT_NUMBER: 443
```
I am using it in combination with an nginx-proxy, which could maybe be the reason for it not working?
Also, feel free to provide the compose file with some changes in the repo, maybe some people will find it useful.

**Comment by elliott-wen** [comment]
Could you try the latest commit again?

Cheers
Elliott

Mirza Arnaut <notifications@github.com> 于2020年7月2日周四 下午1:49写道：

**Comment by SoulEater45** [comment]
Pulled and compiled it now.
The Github button appered now too, which was not there in the prior version.
Playground button works now and redirects me to `<domain>/project.html`

But now some weird loading is happening and in the developer console I get an 502: `<domain>/list?uri=<hash>/manifest` [VM353:1]. After the loading is done, the `create new project` button reacts to the press, but I only get warning `Form submission canceled because the form is not connected` and two further 502s:

`<domain>analytics/r/<hash>?v=1&_v=j83&a=1473105468&t=event&_s=3&dl=https%3A%2F%2F<domain>%2Fproject.html&ul=de-de&de=UTF-8&dt=SwiftLaTeX%3A%20WYSIWYG%20LaTeX%20Editor%20for%20Browsers&sd=24-bit&sr=1920x1080&vp=1323x969&je=0&ec=project&ea=create&el=&_u=CACAAEABC~&jid=565315250&gjid=800634165&cid=1474864248.1593650630&tid=UA-82644344-1&_gid=1003755357.1593650630&_r=1&z=220904618`

`<domain>/upload?uri=<hash>/asset/main.SHeo8.tex`

Also, clicking on the other buttons does open a new tab, but it tries to go to localhost:3011.
Do you have some environment variable which can be changed for the domain to be determened?
If not, maybe I can see to implement it if I get some free time in the next days :)

Also, here are the logs from the building:
<details>
  <summary>Click to expand!</summary>
  
Building apache
Step 1/7 : FROM node:12
 ---> 1fa6026dd8bb
Step 2/7 : WORKDIR /usr/src/app
 ---> Running in 18871355be62
Removing intermediate container 18871355be62
 ---> 1b4d9b737321
Step 3/7 : COPY package*.json ./
 ---> 44aee084374d
Step 4/7 : RUN npm install
 ---> Running in 78c63dc00777

> puppeteer@1.20.0 install /usr/src/app/node_modules/puppeteer
> node install.js


Chromium downloaded to /usr/src/app/node_modules/puppeteer/.local-chromium/linux-686378

> core-js@3.6.5 postinstall /usr/src/app/node_modules/@babel/node/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> core-js@2.6.11 postinstall /usr/src/app/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> nodemon@1.19.4 postinstall /usr/src/app/node_modules/nodemon
> node bin/postinstall || exit 0

Love nodemon? You can now support the project via the open collective:
 > https://opencollective.com/nodemon/donate

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/jest-runtime/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/jest-runner/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/jest-config/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/@jest/test-sequencer/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/@jest/reporters/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/@jest/core/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 1912 packages from 1024 contributors and audited 1928 packages in 91.472s

64 packages are looking for funding
  run `npm fund` for details

found 4648 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
Removing intermediate container 78c63dc00777
 ---> 306f87c04127
Step 5/7 : COPY . .
 ---> ede5cc85e5ed
Step 6/7 : EXPOSE 3011
 ---> Running in ca45bd3c5f1d
Removing intermediate container ca45bd3c5f1d
 ---> e461c3c5d595
Step 7/7 : CMD [ "npm", "run", "start:dev" ]
 ---> Running in ea3025b5647f
Removing intermediate container ea3025b5647f
 ---> 20660578fe76

</details>

**Comment by elliott-wen** [comment]
Kindly allow me more time to look into this. Currently, we have three
options for users to store files.

The first one is playground. Here, I hosted a minio server, so you may need
a access token to connect to my server in your development environment. (I
am thinking switching to public server like play.minio, so I dont have to
host a server. )

Also, we have Dropbox and Google. These two are backend-less, should work
out of the box. Google and Dropbox requires an OAuth callback url, which I
have set it to be localhost:3011/auth.html.

If you want to change it, you may need to register yourself as a developer
and put your own developer ID and callback URL to the source code.



Mirza Arnaut <notifications@github.com> 于2020年7月2日周四 下午2:22写道：

**Comment by elliott-wen** [comment]
The analytics is used for me to collect some error information, you can
turn it off by removing EventReporter.ts if it concerns you.

Elliott Wen <jq.elliott.wen@gmail.com> 于2020年7月2日周四 下午2:30写道：

**Comment by SoulEater45** [comment]
It is not alarming, I understand that you need time to refine the project and I will wait until then :)

Would it be a viable option to host a minio server myself in the future (like in the theia version you had before)?
This would be quite awesome, since I would like it to be hosted on my public server and I don't want everyone having access to it. Hence a password protected storage would be awesome (and turning off the other options). Maybe I am also thinking too far ahead now..

And it is not possible to change the callback url dynamically?

And I do not have any problems with the analytics, since I know everyone can look up the code and not many have the courage to do malice things in hope no one sees it ;)

**Comment by elliott-wen** [comment]
*Would it be a viable option to host a minio server myself in the future
(like in the theia version you had before)?*

Yes, it is absolutely possible. And the new version is implemented with
that in mind. I will keep you updated and the function should be there
relatively soon.

*And it is not possible to change the callback url dynamically?*

Unfortunately, it is not allowed due to limitation of Oauth protocol.  It
is very easy to obtain your own developer ID. I would strongly suggest you
do that if you are using our system in a production environment. It allows
you to design the consent screen and necessary permissions you want to ask
from users.

Cheers
Elliott







Mirza Arnaut <notifications@github.com> 于2020年7月2日周四 下午2:48写道：

**Comment by elliott-wen** [comment]
@SoulEater45 The recent update allows you to use your own minio server. 

Simply change the credential info in src/server/minio.tsx to yours. The playground will now store files in your minio server. 

But you may need to implement your own user authentication mechanism.

**Comment by MichaelEssich** [comment]
I just wanted to say thank your for this great project! Local minio server works for me with the latest release. I'm looking forward to the sharing feature.

**Comment by elliott-wen** [comment]
Thanks mate. I am still working on it. Will let you know when it is done.

MichaelEssich <notifications@github.com> 于2020年7月5日周日 下午8:51写道：

**Comment by SoulEater45** [comment]
Sorry to bother you @elliott-wen, but do you have a discord server or something similar for keeping in touch?
I do not want to make always a github issue if I have some problems or underlying questions.

**Comment by elliott-wen** [comment]
No worries at all. Feel free to make github issues.

I do have a slack channel.

https://join.slack.com/t/swiftlatex/shared_invite/zt-fxd6hgdd-NJUj1E2Zn~hoiGBxD712Zg


Mirza Arnaut <notifications@github.com> 于2020年7月11日周六 上午9:35写道：
