### ISSUE TITLE
Differences with Overleaf

### ISSUE THREAD

**Issue by michaelmior** [SwiftLaTeX/SwiftLaTeX#38]
I noticed that one of the cited differences with Overleaf is realtime collaboration. I'm not sure when this was written, but Overleaf does have [realtime collaboration support](https://www.overleaf.com/learn/how-to/Can_multiple_authors_edit_the_same_file_at_the_same_time%3F) support now.

**Comment by elliott-wen** [comment]
Oops. Thanks for pointing that out. I didn't have much time proofreading
the readme files. I will modify it relatively soon.

Cheers
Elliott

**Comment by michaelmior** [comment]
No problem. I'm familiar with Overleaf and I just discovered SwiftLaTeX so this stuck out to me. I love SwiftLaTeX as an open source project though 😄
