### ISSUE TITLE
Add some command autofill

### ISSUE THREAD

**Issue by pythonbobo** [SwiftLaTeX/SwiftLaTeX#41]
Hi,
I am very happy with your very nice and easy Editor. The WYSIWYG is very nice and useful:)
I now wrote some pages and I miss the autofill for the latex-commands like in VSCODE or similar. Also some automatic brackets (.,{,[,... would be an awesome feature.

Regards

**Comment by elliott-wen** [comment]
Thanks for your feedbacks.

Yes. We are working on it.

The auto completion requires a language server (lsp). We previously used
Digestif, which is written in Lua. Thus it forces us to bundle a Lua
interpreter.

We are currently rewriting Digestif  to JavaScript, which can provide much
higher performance.

Cheers
Elliott

**Comment by elliott-wen** [comment]
Hi, we have pushed a version to SwiftLaTeX with the auto completion. You may need to purge your browser's cache (or wait one day for the cloudflare cache to be expired) in order to use the auto completion. 

Let me know if you encounter any problems.

**Comment by pythonbobo** [comment]
Hi, unfortunately i cannot compile this version myself. I used the released version for Windows the whole time.

**Comment by elliott-wen** [comment]
Oops. I may miss something. will have a look

**Comment by elliott-wen** [comment]
Hi, checkout the latest binaries, which provide the auto-completion functions.
