### ISSUE TITLE
Release a version integrating all CTAN files

### ISSUE THREAD

**Issue by qyxtim** [SwiftLaTeX/SwiftLaTeX#43]
Can you release a version that integrates all CTAN files?
Downloading all required files from CTAN server or mirror server for me costs some time.
I hope that I can do my work without any internet access.

Thank you!

**Comment by elliott-wen** [comment]
Hmm, I feel a little bit hesitated to integrate all CTAN files as they are enormous (several GBs after compression).

It may be better if I instead release a guide on how to build a mirror server? 

Any thoughts?

**Comment by qyxtim** [comment]
I believe you can create a switch that says "save downloaded CTAN files".
Thus, when I reopen the same project or open another project that shares the same CTAN files, I don't need to download these CTAN files again.

**Comment by elliott-wen** [comment]
I guess you make a point, I am considering using service worker to cache all CTAN files, so offline editing is possible when you have compiled your project again. 

Thanks for advice.
