### ISSUE TITLE
Pressing return while on the sign in page text field won't have the expected behavior

### ISSUE THREAD

**Issue by anakimluke** [SwiftLaTeX/SwiftLaTeX#45]
![image](https://user-images.githubusercontent.com/22756345/94645511-636e0e00-02c2-11eb-9f06-59a1ec39639f.png)

Steps to reproduce the problem:
1. Go to https://www.swiftlatex.com/signin and write an email address in the text field.
2. Press the return key.
3. Notice how your URL bar will change to something like `https://www.swiftlatex.com/signin?username=theemail@you.provided` and then go back to the original `https://www.swiftlatex.com/signin`. (I'm not sure what appears exactly, because it happens too quickly. If anyone knows where in the dev console I can look it up, let me know!)
4. The page seems to refresh and your input is lost.
5. I also did not receive an email.

When pressing tab and then return(or space) to select the button, or just by clicking the button, I get the expected behavior:
A message appears telling me to look in my email inbox and I do actually receive the email.

![image](https://user-images.githubusercontent.com/22756345/94646026-b399a000-02c3-11eb-8423-1f5cf3b7b281.png)

**Comment by elliott-wen** [comment]
Thanks for reporting it. We are investigating the issue. 

Sorry, I recently got overwhelmed by my phd thesis. Will keep updating this system ~~
