### ISSUE TITLE
Demo page is not loading

### ISSUE THREAD

**Issue by waliurjs** [SwiftLaTeX/SwiftLaTeX#64]
Demo is not loading, tried VPN but same result. Whole website is down it seems.

<img width="863" alt="Screenshot 2021-07-10 at 11 59 32 PM" src="https://user-images.githubusercontent.com/4123376/125172326-f5ecf780-e1da-11eb-9c57-ff147c8c4d8e.png">

**Comment by guraltsev** [comment]
Same here!

**Comment by monkeydust** [comment]
Same looks down
