### ISSUE TITLE
adding new line adds space after first character in new line

### ISSUE THREAD

**Issue by albertz** [SwiftLaTeX/SwiftLaTeX#7]
The text was
```
A document to get you started. Delete any text you do not want.
```
And I put the cursor after the `started. `, right before the `D`, removed the space, and pressed enter, such that I had this:
```
A document to get you started.
Delete any text you do not want.
```
However, in the visualization, it looks like there is a space after `D`, i.e. it reads like `D elete any text ...`.
<img width="483" alt="Screen Shot 2019-12-05 at 09 02 46" src="https://user-images.githubusercontent.com/59132/70215605-1d95f700-173e-11ea-98c2-8e5c641d8dfd.png">
<img width="332" alt="Screen Shot 2019-12-05 at 09 02 51" src="https://user-images.githubusercontent.com/59132/70215613-22f34180-173e-11ea-9932-c1ff2648670f.png">

**Comment by elliott-wen** [comment]
Yes, I have noticed this bug. Sometimes, redundant spaces are inserted in
PDF view. But when you export the PDF, the spaces will be gone.

I will try to fix the bug soon.

Cheers
