### ISSUE TITLE
How to run on localhost

### ISSUE THREAD

**Issue by Taurus-ZSZ** [SwiftLaTeX/SwiftLaTeX#77]
I'm a newbie, how can I run this project on my local computer? Can you help me?

**Comment by elliott-wen** [comment]
You can download the zip file from the release page. 
Unzip it to a local folder, and go to that folder. You will see many html files, which are use cases of SwiftLatex.
Open a terminal and type `python3 -m http.server . ` (assume you have python in your computer)
You then can go to your browser and visit http://localhost:8000/ and see the demos.

**Comment by elliott-wen** [comment]
You can clone the repo and type make. :)

You may need to set up the emscripten first.

**Comment by Taurus-ZSZ** [comment]
thank you very much
