### ISSUE TITLE
math rendered incorrectly

### ISSUE THREAD

**Issue by albertz** [SwiftLaTeX/SwiftLaTeX#8]
`\[ x^2 + 2x + 1 \]` results in this:
<img width="117" alt="Screen Shot 2019-12-05 at 09 09 34" src="https://user-images.githubusercontent.com/59132/70216010-fee43000-173e-11ea-8e0a-b37b0e421c2a.png">
i.e. baseline kerning of the fonts in math mode seem a bit off; it has the x in 2x a bit raised.
(Reported [here](https://news.ycombinator.com/item?id=21710200).)

**Comment by elliott-wen** [comment]
I am going to open-source the engine part so probably we can look into it together.

Currently, our engine generates HTMLs file directly. Maybe some css faults.
