### ISSUE TITLE
ReferenceError: cwrap is not defined swiftlatexpdftex.js

### ISSUE THREAD

**Issue by feberts** [SwiftLaTeX/SwiftLaTeX#82]
Although the three wasm modules compiled without errors, I had to add some run time functions as compiler arguments. Otherwise, when compiling a TeX document, `swiftlatexpdftex.js` (and the other two modules accordingly) would complain about not defined functions:

```
ReferenceError: cwrap is not defined swiftlatexpdftex.js:1:1687
    compileLaTeXRoutine http://localhost/swiftlatexpdftex.js:1
    onmessage http://localhost/swiftlatexpdftex.js:1
```

The solution was to add `-s EXPORTED_RUNTIME_METHODS='["cwrap", "allocate"]'` to the makefiles.

Has anyone else experienced this issue?

**Comment by v6ak** [comment]
I've seen this issue, too. If affects pdflatex, but not xetex. I guess that some emscripten defaults have changed and some older versions of emscripten would run fine without this change.

Not sure where the parameter belongs to, maybe just for final linking. I've handled it without patching the Makefile, using a little hack:

```
RUN make 'CXX=em++ -s EXPORTED_RUNTIME_METHODS=["cwrap","allocate"]'
```

**Comment by elliott-wen** [comment]
Fixed. Sorry for the delay.
