### ISSUE TITLE
Is the demo working?

### ISSUE THREAD

**Issue by igrep** [SwiftLaTeX/SwiftLaTeX#83]
As far as I tried, any example in https://www.swiftlatex.com/#demo fails with this console output:

> This is pdfTeX, Version 3.14159265-2.6-1.40.21 (SwiftLaTeX PDFTeX 0.3.0) (preloaded format=swiftlatexpdftex)
I can't find the format file `swiftlatexpdftex.fmt'!

**Comment by v6ak** [comment]
It seems that https://texlive2.swiftlatex.com/ has stopped working for some reason, which makes troubles for instances that don't call the setTexliveEndpoint method.

**Comment by feberts** [comment]
Can you use `setTexliveEndpoint` to tell your instance to fetch the files from ctan.org directly? Or do you have to set up your own Texlive-ondemand server?

**Comment by igrep** [comment]
@feberts No, this issue is about the official site's demo https://www.swiftlatex.com/#demo, which I have no permission to modify.

**Comment by elliott-wen** [comment]
Fixed. :D Sorry for the delay.
