### ISSUE TITLE
Question: Why PdfTeX and XeTeX instead of LuaTeX?

### ISSUE THREAD

**Issue by igrep** [SwiftLaTeX/SwiftLaTeX#89]
As a Research Developer at [IIJ Research Laboratory](https://www.iijlab.net/en/), I'm trying to port my company's internal build flow to compile our annual report to Wasm (on browser). Then I got interested in this project.
But while SwiftLaTeX ports PdfTeX and XeTeX to Wasm, our build flow uses LuaTeX.

So I'm curious why did you adopt PdfTeX and XeTeX instead of LuaTeX? I'm open to both adopting SwiftLaTeX as is (if possible) and porting LuaTeX by myself. Did you find any technical difficulties in porting LuaTeX or any other reasons?

**Comment by elliott-wen** [comment]
Hi Yamamoto,

Thanks for your interest in SwiftLateX.

I have not had the chance to port LuaTeX to WASM. It should be doable. But
LuaTeX depends on more third-party libraries. Compiling them to Wasm may be
a challenging task. Please keep me in loop if you manage to make some
progress on LuaTeX.

Cheers
Elliott

**Comment by igrep** [comment]
Close because the question is answered. Thank you! I'll tell you if I try to port LuaTeX!

**Comment by gigiodelchiaro** [comment]
Hey there, any updates on this thread?

**Comment by igrep** [comment]
Unfortunately, I gave up porting to LuaTeX due to the time limit. I won't try it again because I've resigned the job at IIJ.
