### ISSUE TITLE
feature request: add GitHub integration

### ISSUE THREAD

**Issue by albertz** [SwiftLaTeX/SwiftLaTeX#9]
My Latex documents are often in some (maybe private) GitHub repos (or maybe GitLab). It would be very nice if there is some (simple) integration that I can edit these directly, and commit & push changes.
(Not sure exactly how to handle conflicts... Maybe push to an alternative new branch and ignore this problem for now.)

**Comment by elliott-wen** [comment]
Yes. Albert, that's a good idea. I will start looking into it.
