### ISSUE TITLE
Issue with PdfTeXEngine.js Integration

### ISSUE THREAD

**Issue by Srikanth-Mohankumar** [SwiftLaTeX/SwiftLaTeX#93]
I recently attempted to integrate `PdfTeXEngine.js` into my browser and encountered an error. I would appreciate your assistance in resolving this issue.

Here's the error message I received:

```
Uncaught (in promise) ReferenceError: LaTeXEngine is not defined
    at startSwiftLaTeX (sample.html:13:28)
```

Below is the minimal working example (MWE) of the code I used:

```html
<!DOCTYPE html>
<html>
<head>
    <title>SwiftLaTeX Example</title>
    <script type="module" src="PdfTeXEngine.js"></script>
<p>SwiftLaTeX Example</p>
</head>
<body>
    <pre id="output"></pre>
    <script>
        async function startSwiftLaTeX() {
            const engine = new LaTeXEngine();
			await engine.loadEngine();
			engine.writeMemFSFile("main.tex", "\documentclass{...");
            engine.setEngineMainFile("main.tex");
            let r = await engine.compileLaTeX(); 
            document.getElementById('output').textContent = JSON.stringify(r, null, 2);
        }
        window.onload = startSwiftLaTeX;
    </script>
</body>
</html>
```

Any suggestions or guidance would be greatly appreciated.

**Comment by Srikanth-Mohankumar** [comment]
I apologize for my earlier desperation. After much tinkering, I managed to get it to work, and it turned out to be quite straightforward in the end. Feel free to delete this.

**Comment by s-banach** [comment]
How did you solve it?

**Comment by LalitDeore** [comment]
@Srikanth-Mohankumar Hey could you please tell me how you solved this issue? It would be really greate if you could share some minimal example code for how to integrate this in project.
