### ISSUE TITLE
Feature Request: Change Compilation Mode to Scrollmode

### ISSUE THREAD

**Issue by Srikanth-Mohankumar** [SwiftLaTeX/SwiftLaTeX#94]
### Description

I would like to request an option to change the LaTeX compilation mode from `errorstopmode` to `scrollmode`. The intention behind this request is to generate the PDF output even if there are compilation errors. This feature would be very helpful for continuous previewing during the document editing process.

### Proposed Solution

- Add a configuration setting to switch the compilation mode.
- Implement the change in the compilation script to use `scrollmode` instead of `errorstopmode`.

### Additional Context

In `scrollmode`, the LaTeX compiler does not stop at errors, allowing for continuous generation of the PDF output. This would improve the user experience by providing real-time feedback during document creation.

Thank you for considering this request!

**Comment by zhengdechang** [comment]
I also want to get this method, hopefully can be exposed as a method, let js call

**Comment by Srikanth-Mohankumar** [comment]
I have fixed this in my local.
